<?php
/**
 * This is a config file generated by Deux.
 * Deux is a CLI tool for scaffolding WordPress theme.
 *
 * @link https://deux.ribhnux.tech
 * @package Twin Brothers
 * @since 1.0.0
 */

$twin_brothers_config = array(
	'$allowSync' => true,
	'optimize' => true,
	'asset' => array(
		'libs' => array(
			'twitter-bootstrap' => array(
				'source' => 'cdn',
				'search' => 'bootstrap',
				'version' => '4.0.0',
				'files' => array(
					array(
						'ext' => 'css',
						'path' => 'css/bootstrap.css',
						'is_active' => false,
						'deps' => array(),
					),
					array(
						'ext' => 'css',
						'path' => 'css/bootstrap.min.css',
						'is_active' => true,
						'deps' => array(),
					),
					array(
						'ext' => 'js',
						'path' => 'js/bootstrap.js',
						'is_active' => false,
						'deps' => array(
							'jquery',
						),
					),
					array(
						'ext' => 'js',
						'path' => 'js/bootstrap.min.js',
						'is_active' => true,
						'deps' => array(
							'jquery',
						),
					),
				),
			),
			'headroom' => array(
				'source' => 'cdn',
				'search' => 'headroom',
				'version' => '0.9.4',
				'files' => array(
					array(
						'ext' => 'js',
						'path' => 'headroom.js',
						'is_active' => false,
						'deps' => array(),
					),
					array(
						'ext' => 'js',
						'path' => 'headroom.min.js',
						'is_active' => true,
						'deps' => array(),
					),
				),
			),
		),
		'fonts' => array(
			'montserrat' => array(
				'name' => 'Montserrat',
				'variants' => array(
					'400',
				),
				'subsets' => array(
					'latin',
					'latin-ext',
				),
			),
			'open-sans' => array(
				'name' => 'Open Sans',
				'variants' => array(
					'400',
					'600',
				),
				'subsets' => array(
					'latin',
					'latin-ext',
				),
			),
		),
	),
	'plugins' => array(),
	'components' => array(
		'pagination',
		'post-meta',
		'posted-on',
	),
	'imgsize' => array(),
	'filters' => array(),
	'actions' => array(),
	'libraries' => array(
		'class-tgm-plugin-activation',
		'class-primary-menu-nav-walker',
	),
	'helpers' => array(
		'svg-loader',
	),
	'menus' => array(
		'primary' => array(
			'walker' => true,
			'name' => __( 'Primary', 'twin-brothers' ),
			'description' => __( 'Top menu in navigation bar.', 'twin-brothers' ),
		),
		'footer-menu' => array(
			'walker' => false,
			'name' => __( 'Footer Menu', 'twin-brothers' ),
			'description' => __( 'Footer menu in bottom.', 'twin-brothers' ),
		),
	),
	'widgets' => array(
		'sidebar' => array(
			'name' => __( 'Sidebar', 'twin-brothers' ),
			'description' => __( 'Sidebar on the right column.', 'twin-brothers' ),
			'class' => '',
			'before_widget' => '<section id="%1$s" class="widget %2$s">',
			'after_widget' => '</section>',
			'before_title' => '<h2 class="widget-title">',
			'after_title' => '</h2>',
		),
	),
	'features' => array(
		'custom-logo' => array(
			'width' => 60,
			'height' => 60,
			'flex-width' => true,
			'flex-height' => true,
			'header-text' => '',
		),
		'html5' => array(
			'comment-list',
			'comment-form',
			'search-form',
			'gallery',
			'caption',
		),
		'post-thumbnails' => true,
	),
	'customizer' => array(
		'panels' => array(),
		'sections' => array(),
		'settings' => array(),
		'control_types' => array(),
		'controls' => array(),
	),
);
